# Configurations
title:            ODW
longtitle:        OverdriveWiki
author:           OverdriveLab
email:            3458715622@qq.com
description: >
  这里是**一个致力于帮助大家学习研究有机化学和药学和精神病学的网站**

version:          1.0
gitbook_version:  3.2.3

url:              'https://qxdfimd.github.io'
baseurl:          '/jekyll-gitbook'
rss:              RSS

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:collection/:path/

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
  drug:
    output: true
  effect:
    output: true
  others:
    output: true

ordered_collections:
  - pages
  - posts
  - drug
  - effect
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
