            "sharing": {
                "facebook": false,
                "google": false,
                "github": true,
                "github_link": "https://github.com/OverdriveLab",
                "telegram": true,
                "telegram_link": "https://t.me/Qxdfimd",
                "instapaper": false,
                "twitter": true,
                "twitter_link": "https://twitter.com/Qxdfimd_",
                "vk": false,
                "weibo": false,
            },
